#Application context base path
server:
  contextPath: /
  port: 8080
  max-http-header-size: 10000000

#Actuator configuration
management:
  port: 8081
  security:
    enabled: false
  endpoints:
    health:
     id: health
    sensitive: false
    enabled: true
  add-application-context-header: false

#Log level configuration
logging:
  level:
    org:
      ian:
        gohenry: DEBUG
      springframework: ERROR

spring:
  jackson:
    date-format: yyyy-MM-dd
    time-zone: Europe/London
    serialization:
      write-dates-as-timestamps: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

  h2:
    console:
      enabled: true
    path: /h2-console
  datasource:
    url: jdbc:h2:mem:parentDB
    username: sa
    password:
    driverClassName: org.h2.Driver